using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using akabiz_contact.DataSet1TableAdapters;

namespace akabiz_contact
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        ContactTableAdapter kh = new ContactTableAdapter();
        public Form1()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            campaignTypeTableAdapter1.Fill(dataSet12.CampaignType);
            // This line of code is generated by Data Source Configuration Wizard
            contactTableAdapter1.Fill(dataSet13.Contact);
        }

        private void Form1_Load(object sender, EventArgs e)
        {
        
        }
        private void button6_Click(object sender, EventArgs e)
        {

            int t = int.Parse(gridView2.GetRowCellValue(gridView2.FocusedRowHandle, "Id").ToString());
            kh.DeleteQuery(t);
            MessageBox.Show("Xóa thành công (^-^)");
            contactTableAdapter1.Fill(dataSet13.Contact);
        }


        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
        private Form KiemTraTon(Type ftype)
        {
            foreach (Form f in this.MdiChildren)
            {
                if (f.GetType() == ftype)
                {
                    return f;
                }
            }
            return null;
        }
        private void button5_Click(object sender, EventArgs e)
        {
           // XtraForm1 xt = new XtraForm1();
           // xt.ShowDialog();

            Form dn = this.KiemTraTon(typeof(XtraForm1));
            if (dn != null)
            {
                dn.Activate();
            }
            else
            {
                var f = new XtraForm1();
                f.IsMdiContainer = this.IsMdiContainer;
                f.StartPosition = FormStartPosition.CenterScreen;
                f.Show();
            }
        }

        private void button9_Click(object sender, EventArgs e)
        {
            try
            {
                int t = int.Parse(gridView2.GetRowCellValue(gridView2.FocusedRowHandle, "Id").ToString());
                String ten = gridView2.GetRowCellValue(gridView2.FocusedRowHandle, "Name").ToString();
                String uid = gridView2.GetRowCellValue(gridView2.FocusedRowHandle, "Uid").ToString();
                String phone = gridView2.GetRowCellValue(gridView2.FocusedRowHandle, "Phone").ToString();
                String Emial = gridView2.GetRowCellValue(gridView2.FocusedRowHandle, "Email").ToString();
                kh.UpdateQuery(ten, uid, phone, Emial, t);
                MessageBox.Show("Sửa thành công (^-^)");
                contactTableAdapter1.Fill(dataSet13.Contact);
            }
            catch
            {
                MessageBox.Show("Vui lòng kiểm tra lại");
            }
        }
        private void gridView2_CellValueChanged(object sender, DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs e)
        {
            
        }

        private void gridView2_CellValueChanging(object sender, DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs e)
        {
           // textBox1.Text = gridView2.GetRowCellValue(gridView2.FocusedRowHandle, "Id").ToString();
        }

        private void gridView2_ColumnChanged(object sender, EventArgs e)
        {
   //         textBox1.Text = gridView2.GetRowCellValue(gridView2.FocusedRowHandle, "Id").ToString();
        }

        private void gridView2_SelectionChanged(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
            //textBox1.Text = gridView2.GetRowCellValue(gridView2.FocusedRowHandle, "Id").ToString();
        }

        private void gridView2_Click(object sender, EventArgs e)
        {
           // textBox1.Text = gridView2.GetRowCellValue(gridView2.FocusedRowHandle, "Id").ToString();
        }

        private void gridControl2_Click(object sender, EventArgs e)
        {
           
        }
    }

      
}
